"""Add AdminAuthChallenge and AdminUser username phone

Revision ID: 36d3c1f1e7de
Revises: a09381eb2bd9
Create Date: 2026-08-15 19:41:47.746200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d3c1f1e7de'
down_revision: Union[str, Sequence[str], None] = 'a09381eb2bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auth_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('encrypted_session', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_auth_challenges_admin_user_id'), 'admin_auth_challenges', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_auth_challenges_expires_at'), 'admin_auth_challenges', ['expires_at'], unique=False)
    op.add_column('admin_users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('admin_users', sa.Column('phone_number', sa.String(), nullable=True))
    
    # Populate existing rows to avoid null constraint violation
    op.execute("UPDATE admin_users SET username = 'admin', phone_number = '+201000000000' WHERE username IS NULL")
    
    op.alter_column('admin_users', 'username', nullable=False)
    op.alter_column('admin_users', 'phone_number', nullable=False)
    
    op.create_unique_constraint('uq_admin_users_username', 'admin_users', ['username'])
    op.create_unique_constraint('uq_admin_users_phone_number', 'admin_users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.drop_column('admin_users', 'phone_number')
    op.drop_column('admin_users', 'username')
    op.drop_index(op.f('ix_admin_auth_challenges_expires_at'), table_name='admin_auth_challenges')
    op.drop_index(op.f('ix_admin_auth_challenges_admin_user_id'), table_name='admin_auth_challenges')
    op.drop_table('admin_auth_challenges')
    # ### end Alembic commands ###
