"""Add AdminPhoneChangeChallenge

Revision ID: 88c41eb496d1
Revises: 36d3c1f1e7de
Create Date: 2026-08-17 13:01:21.948242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c41eb496d1'
down_revision: Union[str, Sequence[str], None] = '36d3c1f1e7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_phone_change_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('new_phone_number', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_phone_change_challenges_admin_user_id'), 'admin_phone_change_challenges', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_phone_change_challenges_expires_at'), 'admin_phone_change_challenges', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_phone_change_challenges_expires_at'), table_name='admin_phone_change_challenges')
    op.drop_index(op.f('ix_admin_phone_change_challenges_admin_user_id'), table_name='admin_phone_change_challenges')
    op.drop_table('admin_phone_change_challenges')
    # ### end Alembic commands ###
