"""add original_product_id

Revision ID: a09381eb2bd9
Revises: 40b0c18ccb65
Create Date: 2026-08-14 18:03:09.546214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09381eb2bd9'
down_revision: Union[str, Sequence[str], None] = '40b0c18ccb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('original_product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_order_items_original_product_id'), 'order_items', ['original_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_original_product_id'), table_name='order_items')
    op.drop_column('order_items', 'original_product_id')
    # ### end Alembic commands ###
